import 'package:flutter/material.dart';

import '../api_client.dart';
import '../network.dart';
import '../scanning/scan_page.dart';
import '../session.dart';

class BindScreen extends StatefulWidget {
  const BindScreen({super.key, required this.onBound});

  final Future<void> Function(AppSession) onBound;

  @override
  State<BindScreen> createState() => _BindScreenState();
}

class _BindScreenState extends State<BindScreen> {
  final _baseUrlController = TextEditingController(text: 'http://10.0.2.2:4000');
  final _codeController = TextEditingController();
  final _deviceController = TextEditingController(text: 'android-flutter-device');

  bool _submitting = false;
  String? _error;
  String? _urlWarning;

  @override
  void initState() {
    super.initState();
    _urlWarning = _warningFor(_baseUrlController.text);
  }

  String? _warningFor(String url) {
    switch (checkBaseUrl(url)) {
      case BaseUrlVerdict.insecureLan:
        return 'Plain HTTP — acceptable for LAN/localhost, but the token travels unencrypted.';
      case BaseUrlVerdict.insecurePublic:
        return 'Insecure: plain HTTP to a public host. Use HTTPS.';
      case BaseUrlVerdict.secure:
      case BaseUrlVerdict.invalid:
        return null;
    }
  }

  Future<void> _bind() async {
    final baseUrl = _baseUrlController.text.trim();
    final verdict = checkBaseUrl(baseUrl);
    if (verdict == BaseUrlVerdict.invalid) {
      setState(() {
        _error = 'Enter a valid http(s) backend URL.';
      });
      return;
    }
    if (verdict == BaseUrlVerdict.insecurePublic) {
      final proceed = await showDialog<bool>(
        context: context,
        builder: (ctx) => AlertDialog(
          title: const Text('Insecure connection'),
          content: const Text(
            'This backend URL uses plain HTTP on a public host, so the store '
            'token would travel unencrypted. Continue anyway?',
          ),
          actions: [
            TextButton(
              onPressed: () => Navigator.of(ctx).pop(false),
              child: const Text('Cancel'),
            ),
            FilledButton(
              onPressed: () => Navigator.of(ctx).pop(true),
              child: const Text('Continue'),
            ),
          ],
        ),
      );
      if (proceed != true || !mounted) {
        return;
      }
    }

    setState(() {
      _submitting = true;
      _error = null;
    });

    try {
      final api = ApiClient(baseUrl: baseUrl);
      final session = await api.bindStore(
        code: _codeController.text.trim(),
        deviceId: _deviceController.text.trim(),
      );
      await widget.onBound(session);
    } catch (error) {
      setState(() {
        _error = error.toString().replaceFirst('Exception: ', '');
      });
    } finally {
      if (mounted) {
        setState(() {
          _submitting = false;
        });
      }
    }
  }

  Future<void> _scanBindingCode() async {
    final code = await BarcodeScanPage.scan(context, title: 'Scan binding code');
    if (code == null || !mounted) {
      return;
    }
    setState(() {
      _codeController.text = code;
    });
  }

  @override
  void dispose() {
    _baseUrlController.dispose();
    _codeController.dispose();
    _deviceController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Card(
          margin: const EdgeInsets.all(16),
          child: Padding(
            padding: const EdgeInsets.all(16),
            child: ConstrainedBox(
              constraints: const BoxConstraints(maxWidth: 420),
              child: Column(
                mainAxisSize: MainAxisSize.min,
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  Text('Bind Store Device', style: Theme.of(context).textTheme.headlineSmall),
                  const SizedBox(height: 8),
                  const Text('Use one-time binding code generated by admin.'),
                  const SizedBox(height: 16),
                  TextField(
                    controller: _baseUrlController,
                    onChanged: (value) => setState(() {
                      _urlWarning = _warningFor(value);
                    }),
                    decoration: const InputDecoration(labelText: 'Backend URL'),
                  ),
                  if (_urlWarning != null) ...[
                    const SizedBox(height: 4),
                    Text(
                      _urlWarning!,
                      style: const TextStyle(color: Colors.orange, fontSize: 12),
                    ),
                  ],
                  const SizedBox(height: 12),
                  TextField(
                    controller: _codeController,
                    decoration: InputDecoration(
                      labelText: 'Binding code',
                      suffixIcon: IconButton(
                        tooltip: 'Scan binding code',
                        icon: const Icon(Icons.qr_code_scanner),
                        onPressed: _submitting ? null : _scanBindingCode,
                      ),
                    ),
                  ),
                  const SizedBox(height: 12),
                  TextField(
                    controller: _deviceController,
                    decoration: const InputDecoration(labelText: 'Device ID'),
                  ),
                  if (_error != null) ...[
                    const SizedBox(height: 12),
                    Text(_error!, style: const TextStyle(color: Colors.red)),
                  ],
                  const SizedBox(height: 16),
                  FilledButton(
                    onPressed: _submitting ? null : _bind,
                    child: _submitting
                        ? const SizedBox(
                            width: 18,
                            height: 18,
                            child: CircularProgressIndicator(strokeWidth: 2),
                          )
                        : const Text('Bind'),
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}
